 # schema.yml

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "sales of Greenweez"
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        tests:
          - unique:
             column_name: "(pdt_id || '-' || orders_id)"
      - name: product
        identifier: raw_gz_product
        description: "purchase price"
        tests:
          - unique:
              column_name: products_id
          - not_null:
              column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        description: "ship table"
        tests:
          - unique:
              column_name: orders_id
          - not_null:
              column_name: orders_id
models:
   - name: int_sales_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"
       - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [orders_id, products_id]
   - name: int_orders_operational
     description: operational margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: operational_margin
         description: operational_margin = margin + shipping_fee - log_cost - ship_cost
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: shipping_fee
         description: the price the customer pays for shipping
       - name: log_cost
         description: the cost of preparing the parcel in the distribution centre/warehouse
       - name: ship_cost
         description: shipping cost paid by Greenweez to the carrier/logistics provider